[[redirects]]
from = "/music/*"
to = "https://music.163.com/:splat"
status = 200
force = true

[[redirects]]
from = "/icons/*"
to = "https://cdn.simpleicons.org/:splat"
status = 200
force = true

# [[redirects]]
# from = "/cdn/*"
# to = "https://cdn.jsdelivr.net/npm/:splat"
# status = 200
# force = true
